# Generated by Django 5.0.6 on 2024-06-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("header", models.CharField(max_length=9999)),
                ("a", models.CharField(max_length=9999)),
                ("b", models.CharField(max_length=9999)),
                ("c", models.CharField(max_length=9999)),
                ("d", models.CharField(max_length=9999)),
                ("correct_answer", models.CharField(max_length=1)),
                ("answer", models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, null=True, to="all_api.questions"
                    ),
                ),
            ],
        ),
    ]
