# Generated by Django 5.0.6 on 2024-06-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("all_api", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="finish_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="publish_date_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
