# Generated by Django 5.0.6 on 2024-06-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("all_api", "0008_quiz_finish_date_time_quiz_publish_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                default="profile_photo_default.png",
                upload_to="profile_photos/%Y/%m/%d/",
            ),
        ),
    ]
