# Generated by Django 5.0.6 on 2024-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("all_api", "0009_userprofile_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_exp",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_level",
            field=models.IntegerField(default=1),
        ),
    ]
