# Generated by Django 5.0.6 on 2024-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("all_api", "0010_userprofile_user_exp_userprofile_user_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="quiz_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_photos/%Y/%m/%d/"
            ),
        ),
    ]
