# Generated by Django 5.0.6 on 2024-07-08 15:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("all_api", "0011_questions_quiz_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="quiz_photo",
            new_name="question_photo",
        ),
    ]
