# Generated by Django 5.0.6 on 2024-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("all_api", "0013_alter_userprofile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                default="profile_photo_default.png",
                upload_to="profile_photos/%Y/%m/%d/",
            ),
        ),
    ]
